/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __markAsModule = (target) => __defProp(target, "__esModule", { value: true });
var __export = (target, all) => {
  __markAsModule(target);
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __reExport = (target, module2, desc) => {
  if (module2 && typeof module2 === "object" || typeof module2 === "function") {
    for (let key of __getOwnPropNames(module2))
      if (!__hasOwnProp.call(target, key) && key !== "default")
        __defProp(target, key, { get: () => module2[key], enumerable: !(desc = __getOwnPropDesc(module2, key)) || desc.enumerable });
  }
  return target;
};
var __toModule = (module2) => {
  return __reExport(__markAsModule(__defProp(module2 != null ? __create(__getProtoOf(module2)) : {}, "default", module2 && module2.__esModule && "default" in module2 ? { get: () => module2.default, enumerable: true } : { value: module2, enumerable: true })), module2);
};
var __async = (__this, __arguments, generator) => {
  return new Promise((resolve, reject) => {
    var fulfilled = (value) => {
      try {
        step(generator.next(value));
      } catch (e) {
        reject(e);
      }
    };
    var rejected = (value) => {
      try {
        step(generator.throw(value));
      } catch (e) {
        reject(e);
      }
    };
    var step = (x) => x.done ? resolve(x.value) : Promise.resolve(x.value).then(fulfilled, rejected);
    step((generator = generator.apply(__this, __arguments)).next());
  });
};

// src/main.ts
__export(exports, {
  default: () => MoonReader
});
var import_obsidian4 = __toModule(require("obsidian"));

// src/suggester.ts
var import_obsidian = __toModule(require("obsidian"));
var ExportSelecter = class extends import_obsidian.FuzzySuggestModal {
  constructor(app, suggestions) {
    super(app);
    this.setPlaceholder("Choose your export file");
    this.suggestions = suggestions;
    this.submitted = false;
  }
  getItems() {
    return this.suggestions;
  }
  getItemText(item) {
    return `${item.basename}`;
  }
  onChooseItem(item, evt) {
    this.resolve(item);
  }
  selectSuggestion(value, evt) {
    this.submitted = true;
    this.onChooseSuggestion(value, evt);
    this.close();
  }
  onClose() {
    if (!this.submitted) {
      this.reject();
    }
  }
  openAndGetValue() {
    return __async(this, null, function* () {
      return new Promise((resolve, reject) => {
        try {
          this.resolve = resolve;
          this.reject = reject;
          this.open();
        } catch (e) {
          console.log(e);
        }
      });
    });
  }
};

// src/types.ts
var Annotation = class {
};

// src/parseMrexptContents.ts
function parseMrexptContents(highlightContent) {
  const listOfAnnotations = [];
  const regexpHighlight = /#\n(?<id>.*)\n(?<title>.*)\n(?<path>.*)\n(?<lpath>.*)\n(?<chapter>.*)\n(?<p1>.*)\n(?<location>.*)\n(?<characters>.*)\n(?<color>.*)\n(?<timestamp>.*)\n(?<bookmarkText>.*)\n(?<noteText>.*)\n(?<highlightText>.*)\n(?<t1>.*)\n(?<t2>.*)\n(?<t3>.*)\n/g;
  let currentHighlight = regexpHighlight.exec(highlightContent);
  do {
    const annotation = new Annotation();
    const extractedRegexMatch = currentHighlight.groups;
    annotation.sectionNumber = Number(extractedRegexMatch.chapter);
    annotation.location = extractedRegexMatch.location;
    annotation.highlightText = extractedRegexMatch.highlightText.replaceAll("<BR>", "\n");
    annotation.noteText = extractedRegexMatch.noteText.replaceAll("<BR>", "\n");
    annotation.indexCount = Number(extractedRegexMatch.id);
    annotation.annotType1 = Number(extractedRegexMatch.t1);
    annotation.annotType2 = Number(extractedRegexMatch.t2);
    annotation.annotType3 = Number(extractedRegexMatch.t3);
    annotation.bookmarkText = extractedRegexMatch.bookmarkText;
    annotation.unixTimestamp = extractedRegexMatch.timestamp;
    annotation.signedColor = Number(extractedRegexMatch.color);
    annotation.characterCount = Number(extractedRegexMatch.characters);
    annotation.bookName = extractedRegexMatch.title;
    annotation.bookPath = extractedRegexMatch.path;
    listOfAnnotations.push(annotation);
    currentHighlight = regexpHighlight.exec(highlightContent);
  } while (currentHighlight !== null);
  return listOfAnnotations;
}

// src/parser.ts
function parse(content) {
  return parseMrexptContents(content);
}

// src/util.ts
function integerToRGBA(number) {
  if (number < 0) {
    number = 4294967295 + number + 1;
  }
  const ARGB = number.toString(16).toUpperCase();
  const output = `${ARGB.slice(2)}${ARGB.slice(0, 2)}`;
  return output;
}

// src/exporter.ts
function generateOutput(listOfAnnotations, mrexptTFile, colorMappings, enableNewExporter, includeFrontmatter) {
  const sample = listOfAnnotations[0];
  if (!sample)
    return "";
  const colorToCallout = new Map();
  for (const mapping of colorMappings) {
    colorToCallout.set(mapping.signedColor, {
      type: mapping.calloutType,
      title: mapping.calloutTitle || ""
    });
  }
  const selectedColors = new Set(colorMappings.map((m) => m.signedColor));
  let output = "";
  if (includeFrontmatter) {
    output += `---
path: "${mrexptTFile.path}"
title: "${sample.bookName}"
author: 
lastExportedTimestamp: ${mrexptTFile.stat.mtime}
lastExportedID: ${listOfAnnotations[listOfAnnotations.length - 1].indexCount}
tags: 
  - "review/book"
---

`;
  }
  const filteredAnnotations = listOfAnnotations.filter((a) => selectedColors.has(a.signedColor));
  for (const annotation of filteredAnnotations) {
    if (annotation.highlightText || annotation.noteText) {
      output += `${template(annotation, enableNewExporter, colorToCallout)}
`;
    }
  }
  return output;
}
function template(annotation, enableNewExporter, colorToCallout) {
  let { indexCount, highlightText: highlight, noteText: note, signedColor } = annotation;
  if (enableNewExporter) {
    if (note.trim() === "#") {
      return `# ${highlight.replace("\n", ": ")}
`;
    }
    if (note.trim() === "##") {
      return `## ${highlight.replace("\n", ": ")}
`;
    }
    if (note.trim() === "###") {
      return `### ${highlight.replace("\n", ": ")}
`;
    }
    return `> [!notes] ${indexCount}
${highlight.split("\n").map((t) => `> ${t}`).join("\n")}
> ***
${note.split("\n").map((t) => `> ${t}`).join("\n")}
`;
  } else {
    const mapped = colorToCallout.get(signedColor);
    const calloutType = (mapped == null ? void 0 : mapped.type) || integerToRGBA(signedColor).slice(0, 6);
    const calloutTitle = (mapped == null ? void 0 : mapped.title) || "";
    if (highlight.includes("\n")) {
      highlight = highlight.replaceAll("\n", "\n> ");
    }
    let calloutHeader = `> [!${calloutType}]`;
    if (calloutTitle) {
      calloutHeader += ` ${calloutTitle}`;
    }
    let result = `${calloutHeader}
`;
    result += `> ${highlight}
`;
    if (note && note.trim()) {
      result += `> ***
`;
      const noteLines = note.split("\n");
      for (const line of noteLines) {
        result += `> ${line}
`;
      }
    }
    return result;
  }
}

// src/settings.ts
var import_obsidian2 = __toModule(require("obsidian"));
var SettingsTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian2.Setting(containerEl).setName("Book Exports Path").setDesc("This is where your .mrexpt files are stored.").addText((text) => text.setPlaceholder("Book Exports").setValue(this.plugin.settings.exportsPath).onChange((value) => __async(this, null, function* () {
      this.plugin.settings.exportsPath = value;
      yield this.plugin.saveSettings();
    })));
    new import_obsidian2.Setting(containerEl).setName("Include file header (frontmatter)").setDesc("Add YAML frontmatter (path, title, timestamp, tags) at the top of the output. Turn off if you have your own note structure.").addToggle((toggle) => toggle.setValue(this.plugin.settings.includeFrontmatter).onChange((value) => __async(this, null, function* () {
      this.plugin.settings.includeFrontmatter = value;
      yield this.plugin.saveSettings();
    })));
    new import_obsidian2.Setting(containerEl).setName("Experimental Support for SRS").setDesc(createFragment((frag) => {
      frag.appendText("Enable support for ");
      frag.createEl("a", {
        text: "AB1908's new SRS plugin",
        href: "https://github.com/AB1908/obsidian-spaced-repetition/"
      }, (a) => {
        a.setAttr("target", "_blank");
      });
      frag.appendText(". This will change the output format.");
    })).addToggle((toggle) => toggle.setValue(this.plugin.settings.enableSRSSupport).onChange((value) => __async(this, null, function* () {
      return yield this.updateSettings({ enableSRSSupport: value });
    })));
    containerEl.createEl("hr");
    containerEl.createEl("h3", { text: "Color \u2192 Callout Mapping" });
    containerEl.createEl("p", {
      text: "Map each Moon+ Reader highlight color to an Obsidian callout type. You can also set a custom title that appears after the callout type, e.g. [!quote] My Custom Title."
    });
    const mappings = this.plugin.settings.colorMappings;
    if (mappings.length === 0) {
      containerEl.createEl("p", { text: "No color mappings configured. Parse an export first to auto-discover colors." });
    } else {
      mappings.forEach((mapping, index) => {
        this.addColorMappingSetting(containerEl, mapping, index);
      });
    }
    new import_obsidian2.Setting(containerEl).setName("Add color mapping").setDesc("Manually add a color-to-callout mapping").addButton((btn) => btn.setButtonText("+ Add").onClick(() => __async(this, null, function* () {
      this.plugin.settings.colorMappings.push({
        signedColor: 0,
        calloutType: "note",
        calloutTitle: "",
        enabled: true
      });
      yield this.plugin.saveSettings();
      this.display();
    })));
    new import_obsidian2.Setting(containerEl).setName("Reset to defaults").setDesc("Remove all custom mappings and restore defaults").addButton((btn) => btn.setButtonText("Reset").setWarning().onClick(() => __async(this, null, function* () {
      this.plugin.settings.colorMappings = [
        { signedColor: -11184811, calloutType: "cite", calloutTitle: "", enabled: true },
        { signedColor: -2029999361, calloutType: "quote", calloutTitle: "", enabled: true },
        { signedColor: -2013331371, calloutType: "note", calloutTitle: "", enabled: true },
        { signedColor: -2013294080, calloutType: "warning", calloutTitle: "", enabled: true },
        { signedColor: -2013266176, calloutType: "important", calloutTitle: "", enabled: true },
        { signedColor: -1543340033, calloutType: "info", calloutTitle: "", enabled: true },
        { signedColor: -1525467669, calloutType: "tip", calloutTitle: "", enabled: true }
      ];
      yield this.plugin.saveSettings();
      this.display();
    })));
  }
  addColorMappingSetting(containerEl, mapping, index) {
    const hexColor = integerToRGBA(mapping.signedColor).slice(0, 6);
    const setting = new import_obsidian2.Setting(containerEl);
    setting.setName(createFragment((frag) => {
      const colorBox = frag.createEl("span", {
        attr: {
          style: `display: inline-block; width: 16px; height: 16px; border-radius: 3px; background-color: #${hexColor}; border: 1px solid var(--background-modifier-border); vertical-align: middle; margin-right: 8px;`
        }
      });
      frag.appendText(`#${hexColor}`);
    }));
    setting.addText((text) => text.setPlaceholder("type (e.g. note)").setValue(mapping.calloutType).onChange((value) => __async(this, null, function* () {
      this.plugin.settings.colorMappings[index].calloutType = value;
      yield this.plugin.saveSettings();
    })));
    setting.addText((text) => text.setPlaceholder("title (optional)").setValue(mapping.calloutTitle || "").onChange((value) => __async(this, null, function* () {
      this.plugin.settings.colorMappings[index].calloutTitle = value;
      yield this.plugin.saveSettings();
    })));
    setting.addToggle((toggle) => toggle.setValue(mapping.enabled).onChange((value) => __async(this, null, function* () {
      this.plugin.settings.colorMappings[index].enabled = value;
      yield this.plugin.saveSettings();
    })));
    setting.addExtraButton((btn) => btn.setIcon("trash").setTooltip("Remove this mapping").onClick(() => __async(this, null, function* () {
      this.plugin.settings.colorMappings.splice(index, 1);
      yield this.plugin.saveSettings();
      this.display();
    })));
  }
  updateSettings(settings) {
    return __async(this, null, function* () {
      Object.assign(this.plugin.settings, settings);
      yield this.plugin.saveSettings();
    });
  }
};

// src/colorpicker.ts
var import_obsidian3 = __toModule(require("obsidian"));
var ColorPicker = class extends import_obsidian3.Modal {
  constructor(app, mappings) {
    super(app);
    this.mappings = mappings;
    this.selectedColors = new Set(mappings.filter((m) => m.enabled).map((m) => m.signedColor));
    this.submitted = false;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Select colors to import" });
    contentEl.createEl("p", {
      text: "Choose which colors to import. Click the toggle to include/exclude each color.",
      attr: { style: "color: var(--text-muted); font-size: 0.9em; margin-bottom: 16px;" }
    });
    for (const mapping of this.mappings) {
      this.addMappingRow(contentEl, mapping);
    }
    new import_obsidian3.Setting(contentEl).addButton((btn) => btn.setButtonText("Select All").onClick(() => {
      this.mappings.forEach((m) => this.selectedColors.add(m.signedColor));
      this.refreshUI();
    })).addButton((btn) => btn.setButtonText("Deselect All").onClick(() => {
      this.selectedColors.clear();
      this.refreshUI();
    })).addButton((btn) => btn.setButtonText("Import Selected").setCta().onClick(() => {
      this.submitted = true;
      const selected = this.mappings.filter((m) => this.selectedColors.has(m.signedColor));
      this.resolve(selected);
      this.close();
    }));
  }
  addMappingRow(containerEl, mapping) {
    const hexColor = integerToRGBA(mapping.signedColor).slice(0, 6);
    const isSelected = this.selectedColors.has(mapping.signedColor);
    const setting = new import_obsidian3.Setting(containerEl);
    setting.setName(createFragment((frag) => {
      const colorBox = frag.createEl("span", {
        attr: {
          style: `display: inline-block; width: 14px; height: 14px; border-radius: 3px; background-color: #${hexColor}; border: 1px solid var(--background-modifier-border); vertical-align: middle; margin-right: 8px;`
        }
      });
      frag.appendText(`#${hexColor}`);
    }));
    const calloutDisplay = mapping.calloutTitle ? `\u2192 [!${mapping.calloutType}] ${mapping.calloutTitle}` : `\u2192 [!${mapping.calloutType}]`;
    setting.setDesc(calloutDisplay);
    setting.addToggle((toggle) => toggle.setValue(isSelected).onChange((value) => {
      if (value) {
        this.selectedColors.add(mapping.signedColor);
      } else {
        this.selectedColors.delete(mapping.signedColor);
      }
    }));
  }
  refreshUI() {
    this.onOpen();
  }
  onClose() {
    var _a;
    const { contentEl } = this;
    contentEl.empty();
    if (!this.submitted) {
      const selected = this.mappings.filter((m) => this.selectedColors.has(m.signedColor));
      if (selected.length > 0) {
        this.resolve(selected);
      } else {
        (_a = this.reject) == null ? void 0 : _a.call(this, "No colors selected");
      }
    }
  }
  openAndGetValue() {
    return __async(this, null, function* () {
      return new Promise((resolve, reject) => {
        try {
          this.resolve = resolve;
          this.reject = reject;
          this.open();
        } catch (e) {
          console.log(e);
          reject(String(e));
        }
      });
    });
  }
};

// src/main.ts
var DEFAULT_COLOR_MAPPINGS = [
  { signedColor: -11184811, calloutType: "cite", calloutTitle: "", enabled: true },
  { signedColor: -2029999361, calloutType: "quote", calloutTitle: "", enabled: true },
  { signedColor: -2013331371, calloutType: "note", calloutTitle: "", enabled: true },
  { signedColor: -2013294080, calloutType: "warning", calloutTitle: "", enabled: true },
  { signedColor: -2013266176, calloutType: "important", calloutTitle: "", enabled: true },
  { signedColor: -1543340033, calloutType: "info", calloutTitle: "", enabled: true },
  { signedColor: -1525467669, calloutType: "tip", calloutTitle: "", enabled: true }
];
var MOONREADER_DEFAULT_SETTINGS = {
  exportsPath: "Book Exports",
  enableSRSSupport: false,
  includeFrontmatter: true,
  colorMappings: DEFAULT_COLOR_MAPPINGS
};
var MoonReader = class extends import_obsidian4.Plugin {
  onload() {
    return __async(this, null, function* () {
      yield this.loadSettings();
      this.addRibbonIcon("book", "Moon Reader", () => __async(this, null, function* () {
        return yield this.start();
      }));
      this.addCommand({
        id: "parse-exports",
        name: "Parse an export",
        editorCallback: () => __async(this, null, function* () {
          return yield this.start();
        })
      });
      this.addSettingTab(new SettingsTab(this.app, this));
    });
  }
  start() {
    return __async(this, null, function* () {
      var _a;
      const currentTFile = this.app.workspace.getActiveFile();
      if (!currentTFile) {
        new import_obsidian4.Notice("No active file!");
        return;
      }
      const rootPath = this.settings.exportsPath;
      const exportTFolder = this.app.vault.getAbstractFileByPath(rootPath);
      let exportedFiles;
      if (exportTFolder instanceof import_obsidian4.TFolder) {
        exportedFiles = (_a = exportTFolder.children) == null ? void 0 : _a.filter((t) => t instanceof import_obsidian4.TFile && t.basename && t.extension == `mrexpt`).map((t) => t);
      } else {
        new import_obsidian4.Notice("Invalid Folder Path");
        return;
      }
      if (!exportedFiles.length) {
        new import_obsidian4.Notice("Folder does not have any Moon+ Reader exports!");
        return;
      }
      const suggesterModal = new ExportSelecter(this.app, exportedFiles);
      const mrexptChoice = yield suggesterModal.openAndGetValue().catch((e) => {
        new import_obsidian4.Notice("Prompt cancelled");
      });
      if (!mrexptChoice) {
        return;
      }
      const parsedOutput = parse(yield this.app.vault.read(mrexptChoice));
      if (!parsedOutput || parsedOutput.length === 0) {
        new import_obsidian4.Notice("Nothing added!");
        return;
      }
      const colorsInFile = new Set();
      parsedOutput.forEach((t) => colorsInFile.add(t.signedColor));
      let mappingsChanged = false;
      for (const color of colorsInFile) {
        if (!this.settings.colorMappings.some((m) => m.signedColor === color)) {
          this.settings.colorMappings.push({
            signedColor: color,
            calloutType: "note",
            calloutTitle: "",
            enabled: true
          });
          mappingsChanged = true;
        }
      }
      if (mappingsChanged) {
        yield this.saveSettings();
      }
      const relevantMappings = this.settings.colorMappings.filter((m) => colorsInFile.has(m.signedColor));
      const colorModal = new ColorPicker(this.app, relevantMappings);
      const selectedMappings = yield colorModal.openAndGetValue().catch(() => null);
      if (!selectedMappings || selectedMappings.length === 0) {
        new import_obsidian4.Notice("No colors selected!");
        return;
      }
      for (const mapping of this.settings.colorMappings) {
        mapping.enabled = selectedMappings.some((sm) => sm.signedColor === mapping.signedColor);
      }
      yield this.saveSettings();
      const output = generateOutput(parsedOutput, mrexptChoice, selectedMappings, this.settings.enableSRSSupport, this.settings.includeFrontmatter);
      yield this.app.vault.append(currentTFile, output);
      new import_obsidian4.Notice(`Imported ${parsedOutput.filter((a) => selectedMappings.some((m) => m.signedColor === a.signedColor)).length} annotations (${selectedMappings.length} colors)`);
    });
  }
  loadSettings() {
    return __async(this, null, function* () {
      this.settings = Object.assign({}, MOONREADER_DEFAULT_SETTINGS, yield this.loadData());
    });
  }
  saveSettings() {
    return __async(this, null, function* () {
      yield this.saveData(this.settings);
    });
  }
};
